### ISSUE TITLE
chopstix driver: error: Tracer:: track_mmap: Child did not stop

### ISSUE THREAD

**Issue by YiFeiSong-ict** [IBM/chopstix#55]
chop trace -begin 100 -end 300 ./hello_world
Error occurs：chopstix driver: error: Tracer:: track_mmap: Child did not stop
I find the status_ get 0 after waitpid, and the correct stopped signal should be 5 (status_ = 1407).

**Comment by rbertran** [comment]
The _Child did not stop_ error is the result of not providing the right set of begin addresses. If child did not step, it is because the `-begin address` of `100` is never executed. You might need to use other set of addresses. Please check the updated documentation on how to do so.  To trace the function `my_func` you can use:

    chop-marks ./hello_world my_func
    
to get the begin/end addresses to use. Closing the issue.
